lang: "en-gb"
tabcomplete:
  lowcpu: false
data:
  flatfile: true
  mongourl: "mongodb://localhost:27017/"
pvp:
  beheading: true
  keepItemsOnMurder: true
  experiencePenalty: 0.25
mail:
  shulkerFee: 5
  fee: 0
spectator:
  ticksAllowed: 6000
biomeChange:
  chance: 25
  onlyOverworld: true
  bonemeal: true
  naturalGrowth: true
hardcore:
  enabled: true
  hearts: true
  permban: false
  banlength: 120
  lives: 3
  livestheft: false
  regentime: 1200