name: Foundation
version: Alpha 1
main: uk.lsuth.mc.foundation.FoundationCore

api-version: 1.15
depend: [Vault,ProtocolLib]

commands:
  tp:
    description: Teleports player to another location
    usage: /tp <x> <y> <z>, /tp <player>, /tp <warp>
    aliases:
      - "teleport"
      - "warp"
  ping:
    description: Plays a sound to another player
    usage: /ping <player>, /ping <player> <message>
  mint:
    description: Creates currency from gold
    usage: /mint <ingots>
  bal:
    description: Shows your account balance
    usage: /bal
    aliases:
      - "balance"
  query:
    description: Looks for items in nearby containers
    usage: /query <item>, /query <item> <radius>
  slab:
    description: Toggle the conversion of blocks to half-slabs
    usage: /slab
  toast:
    description: Send a toast to a Foundation-Fabric player
    usage: /toast <message>
  msg:
    description: Message a friend secretly
    usage: /msg <player> <message>
    aliases:
      - "m"
      - "message"
  nickname:
    description: Change your nickname
    usage: /nickname <name>, /nickname remove
    aliases:
      - "nick"
  mail:
    description: Allows mailing of items to other players
    usage: /mail send <player>, /mail get
  prefab:
    description: Instantly create a prefabricated house
    usage: /prefab <structure> offset-x offset-y offset-z
  marker:
    description: Create or list markers
    usage: /marker, /marker <name>
  freeze:
    description: Freeze a player
    usage: /freeze <player>
  navigate:
    description: Point your compass in the direction of a marker
    usage: /navigate, /navigate <marker>
    aliases:
      - "nav"
  setmarker:
    description: Set a marker using specified coordinates
    usage: /setmarker <name> <x> <y> <z>, /setmarker <name> <x> <y> <z> <world>
  announce:
    description: Send an announcement to the entire server
    usage: /announce <message>
  restart:
    description: Restart the server
    usage: /restart, /restart <time>
    aliases:
      - restartserver
  where:
    description: Locate a player
    usage: /where is <player>, /where am I
  invoice:
    description: Used to demand money from other players, and pay other players
    usage: /invoice send <amount>, /invoice pay
  transfer:
    description: Used to transfer money to other players
    usage: /transfer <player> <amount>
  assemble:
    description: Call all mobs to you
    usage: /assemble
  shadowkick:
    description: Stop sending keepAlive packets to a player, causing their client to time out.
    usage: /shadowkick <player>
  shadowban:
    description: On login, never send the Success packet to the player.
    usage: /shadowban <player>
  afk:
    description: Mark yourself as AFK
    usage: /afk
  spectate:
    description: Switch to spectator mode
    usage: /spectator
  ride:
    description: Ride anything
    usage: /ride
  lives:
    description: Check hardcore lives
    usage: /lives, /lives <player>
  found:
    description: Access items that have burnt or despawned
    usage: /found, /lost
    aliases:
      - "lost"
  moon:
    description: Check moon phase
    usage: /moon
    aliases:
      - "moonphase"